name: food
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_platform_widgets: ^9.0.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  flutter_local_notifications: ^19.4.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get: ^4.7.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  smooth_page_indicator: ^1.2.1
  geolocator: ^14.0.1
  introduction_screen: ^4.0.0
  font_awesome_flutter: ^10.8.0
  pinput: ^5.0.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^6.0.0
  confetti: ^0.8.0
  avatar_glow: ^3.0.1
  loading_overlay: ^0.4.2
  flutter_spinkit: ^5.2.1
  form_field_validator: ^1.1.0
  timer_count_down: ^2.2.2
  uuid: ^4.5.1
  floor: ^1.5.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  skeletonizer: ^2.1.0+1
  ionicons: ^0.2.2
  timeago: ^3.7.1
  cloud_firestore: ^6.0.2
  geocoding: ^4.0.0
  http: ^1.4.0
  intl: ^0.19.0
  permission_handler: ^12.0.0+1
  path: ^1.9.0
  meta: ^1.15.0
  image_picker: ^1.0.7
  file_picker: ^10.3.3
  imagekit_io: ^0.0.3
  mime: ^2.0.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.2.6
  flutter_inappwebview: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  crypto: ^3.0.5
  cryptography: ^2.7.0
  dio: ^4.0.6
  pointycastle: ^3.9.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  mockito: ^5.4.4
  mocktail: ^1.0.3
  bloc_test: ^10.0.0


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    color: "#ffffff"
    android: true
    ios: true
    image: assets/splash_food_logo.png
  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/
    - .env
    - firebase_seed_data/
